sudo: false
language: node_js
cache:
  yarn: true
notifications:
  email: false
node_js:
  - '9'
  - '8'
  - '6'
  - '4'
script:
  - yarn test
  - yarn danger ci
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
